package io.knotra;

public enum DiagnosticCode {
    MISSING_CAPABILITY,
    CAPABILITY_SLOT_OCCUPIED,
    CAPABILITY_TYPE_CONFLICT,
    BINDING_CYCLE,
    ACTIVATION_FAILED,
    ROLLBACK_FAILED,
    CLEANUP_FAILED,
    NON_CONVERGENT_RECONCILE,
    INVALID_LIFECYCLE_OPERATION,
    INVALID_MOUNT_ID,
    INVALID_CONFIG
}
