package io.knotra.loader;

public enum LoaderDiagnosticCode {
    RESOLUTION_FAILED,
    CONFIG_INVALID,
    INVALID_TREE,
    BASE_UNAVAILABLE,
    CONTEXT_CONFLICT,
    STRUCTURE_REJECTED,
    TEARDOWN_FAILED,
    REPLACEMENT_BLOCKED,
    COMPENSATION_FAILED,
    ACTIVATION_FAILED,
    CLOSED
}
